pipeline {
   agent any
   
   stages {
       
        stage('EnterUserInput') {
         steps {
             script {
                 
                 fh = new File('file1.csv')
                 def csv_content = fh.getText('utf-8')
                 def data_iterator = parseCsv(csv_content)
                     
             }}   
        }
        
         stage('Upload a CSV') {
         steps {
             script {
                 
                        for (line in data_iterator) {
                            output = line[2]
                            if(output == line[1]) {
                                 println "value is match"
                            } else { 
                                 println "value is not match"
                            }
                        }
          
                        
         
      }
       
   }
  }











 
